// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A course recommendation AI agent.
 *
 * - recommendCourses - A function that handles the course recommendation process.
 * - RecommendCoursesInput - The input type for the recommendCourses function.
 * - RecommendCoursesOutput - The return type for the recommendCourses function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendCoursesInputSchema = z.object({
  interests: z
    .string()
    .describe('The interests of the user, comma separated.'),
  pastEnrollment: z
    .string()
    .optional()
    .describe('The past enrolled courses of the user, comma separated.'),
  searchHistory: z
    .string()
    .optional()
    .describe('The search history of the user, comma separated.'),
});
export type RecommendCoursesInput = z.infer<typeof RecommendCoursesInputSchema>;

const RecommendCoursesOutputSchema = z.object({
  courses: z
    .string()
    .describe('The recommended courses for the user, comma separated.'),
});
export type RecommendCoursesOutput = z.infer<typeof RecommendCoursesOutputSchema>;

export async function recommendCourses(input: RecommendCoursesInput): Promise<RecommendCoursesOutput> {
  return recommendCoursesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendCoursesPrompt',
  input: {schema: RecommendCoursesInputSchema},
  output: {schema: RecommendCoursesOutputSchema},
  prompt: `You are an expert in recommending courses to users.

You will use the following information to recommend courses to the user.

Interests: {{{interests}}}
Past Enrollment: {{{pastEnrollment}}}
Search History: {{{searchHistory}}}

Recommend courses to the user based on their interests, past enrollment, and search history.
`,
});

const recommendCoursesFlow = ai.defineFlow(
  {
    name: 'recommendCoursesFlow',
    inputSchema: RecommendCoursesInputSchema,
    outputSchema: RecommendCoursesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
