import type { Course, CourseCategory, Testimonial } from './types';
import { LayoutDashboard, Code, BarChart3, Palette, Camera, Mic2 } from 'lucide-react';

export const courseCategories: CourseCategory[] = [
  { name: 'ব্যবসা', icon: BarChart3 },
  { name: 'ডেভেলপমেন্ট', icon: Code },
  { name: 'মার্কেটিং', icon: Mic2 },
  { name: 'ডিজাইন', icon: Palette },
  { name: 'আইটি ও সফটওয়্যার', icon: LayoutDashboard },
  { name: 'ফটোগ্রাফি', icon: Camera },
];

export const allCourses: Course[] = [
  {
    id: 1,
    title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
    description: 'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Router, Next.js, Best Practices and way more!',
    category: 'ডেভেলপমেন্ট',
    level: 'শিক্ষানবিশ',
    price: 84.99,
    duration: '48.5 ঘণ্টা',
    instructor: { name: 'Maximilian Schwarzmüller', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.6,
    reviewCount: 178000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Build powerful, fast, user-friendly and reactive web apps', 'Provide amazing user experiences by leveraging the power of JavaScript with ease', 'Apply for high-paid jobs or work as a freelancer in one the most demanded sectors you can find in web dev right now'],
    isFeatured: true,
  },
  {
    id: 2,
    title: 'The Complete 2024 Web Development Bootcamp',
    description: 'Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps.',
    category: 'ডেভেলপমেন্ট',
    level: 'শিক্ষানবিশ',
    price: 89.99,
    duration: '61.5 ঘণ্টা',
    instructor: { name: 'Dr. Angela Yu', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.7,
    reviewCount: 345000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Build any website you want.', 'Craft a portfolio of websites to apply for junior developer jobs.', 'Build fully-fledged websites and web apps for your startup or business.'],
    isFeatured: true,
  },
  {
    id: 3,
    title: 'The Ultimate Drawing Course - Beginner to Advanced',
    description: 'Learn the #1 most important building block of all art, Drawing. This course will teach you in a logical, easy to grasp way.',
    category: 'ডিজাইন',
    level: 'শিক্ষানবিশ',
    price: 49.99,
    duration: '11 ঘণ্টা',
    instructor: { name: 'Jaysen Batchelor', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.6,
    reviewCount: 111000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Draw objects out of your head', 'Understand the fundamentals of art', 'Draw realistic light and shadow'],
    isFeatured: true,
  },
  {
    id: 4,
    title: 'Digital Marketing Masterclass - 23 Courses in 1',
    description: 'Grow Your Business with Digital Marketing: Social Media Marketing, Content Marketing, SEO, YouTube, Email Marketing, Facebook, Ads & more',
    category: 'মার্কেটিং',
    level: 'শিক্ষানবিশ',
    price: 94.99,
    duration: '34 ঘণ্টা',
    instructor: { name: 'Phil Ebiner', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.5,
    reviewCount: 88000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Grow a Business Online from Scratch', 'Make Money as a Digital Marketing Freelancer', 'Get Hired as a Digital Marketing Expert'],
    isFeatured: true,
  },
  {
    id: 5,
    title: 'Python for Data Science and Machine Learning Bootcamp',
    description: 'Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, Tensorflow, and more!',
    category: 'আইটি ও সফটওয়্যার',
    level: 'মধ্যবর্তী',
    price: 99.99,
    duration: '25 ঘণ্টা',
    instructor: { name: 'Jose Portilla', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.6,
    reviewCount: 125000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Use Python for Data Science and Machine Learning', 'Implement Machine Learning Algorithms', 'Learn to use Pandas for Data Analysis'],
    isFeatured: false,
  },
  {
    id: 6,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    description: 'The Best Online Professional Photography Class: How to Take Amazing Photos for Beginners & Advanced Photographers.',
    category: 'ফটোগ্রাফি',
    level: 'শিক্ষানবিশ',
    price: 94.99,
    duration: '23.5 ঘণ্টা',
    instructor: { name: 'Phil Ebiner', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.7,
    reviewCount: 65000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['You will know how to take amazing photos that impress your family and friends', 'You will know how the camera truly works, so you can take better photos using manual settings', 'You will know how to compose photos beautifully with basic photography rules'],
    isFeatured: false,
  },
  {
    id: 7,
    title: 'An Entire MBA in 1 Course: Award Winning Business School Prof',
    description: 'Everything you need to know about business from start-up to IPO. The most popular business course on Udemy!',
    category: 'ব্যবসা',
    level: 'শিক্ষানবিশ',
    price: 89.99,
    duration: '8.5 ঘণ্টা',
    instructor: { name: 'Chris Haroun', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.5,
    reviewCount: 75000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Supercharge your financial skills', 'Understand how monetary policy and fiscal policy work', 'Analyze company financials with ease'],
    isFeatured: false,
  },
  {
    id: 8,
    title: 'AWS Certified Solutions Architect - Associate 2024',
    description: 'Pass the AWS Certified Solutions Architect Associate Certification SAA-C03. Includes 2 practice tests!',
    category: 'আইটি ও সফটওয়্যার',
    level: 'মধ্যবর্তী',
    price: 84.99,
    duration: '27 ঘণ্টা',
    instructor: { name: 'Stephane Maarek', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.7,
    reviewCount: 220000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Pass the AWS Certified Solutions Architect Associate (SAA-C03) exam', 'Design and Deploy scalable, highly available, and fault tolerant systems on AWS', 'Become a Cloud Guru'],
    isFeatured: false,
  }
];

export const featuredCourses = allCourses.filter(course => course.isFeatured);

export const testimonials: Testimonial[] = [
  {
    name: 'সারাহ ইসলাম',
    title: 'ওয়েব ডেভেলপার',
    quote: 'ওয়েব ডেভেলপমেন্ট বুটক্যাম্পটি আমার ক্যারিয়ারের জন্য একটি গেম-চেঞ্জার ছিল। প্রশিক্ষকরা জ্ঞানী ছিলেন এবং পাঠ্যক্রমটি পুরোপুরিভাবে সাজানো ছিল।',
    avatar: 'https://placehold.co/80x80.png',
  },
  {
    name: 'মাইকেল চৌধুরী',
    title: 'ডেটা বিশ্লেষক',
    quote: 'পাইথন ফর ডেটা সায়েন্স কোর্সটি শেষ করার পর আমি আমার স্বপ্নের চাকরি পেতে সক্ষম হয়েছি। হাতে-কলমে প্রকল্পগুলো অবিশ্বাস্যভাবে মূল্যবান ছিল।',
    avatar: 'https://placehold.co/80x80.png',
  },
  {
    name: 'এমিলি রহমান',
    title: 'ইউএক্স/ইউআই ডিজাইনার',
    quote: 'স্কিল নেভিগেটরের ডিজাইন কোর্সগুলো আমাকে একটি শক্তিশালী পোর্টফোলিও তৈরি করতে সাহায্য করেছে। এখানকার কমিউনিটি খুবই সহায়ক এবং বিষয়বস্তু শীর্ষস্থানীয়।',
    avatar: 'https://placehold.co/80x80.png',
  },
    {
    name: 'ডেভিড খান',
    title: 'মার্কেটিং ম্যানেজার',
    quote: 'ডিজিটাল মার্কেটিং মাস্টারক্লাসটি আমার যা যা জানার দরকার ছিল তার সবকিছুই কভার করেছে। এরপর থেকে আমার কোম্পানির অনলাইন উপস্থিতি উল্লেখযোগ্যভাবে বৃদ্ধি পেয়েছে।',
    avatar: 'https://placehold.co/80x80.png',
  },
  {
    name: 'জেসিকা আক্তার',
    title: 'ফটোগ্রাফার',
    quote: 'আমি একজন সম্পূর্ণ শিক্ষানবিশ থেকে একজন আত্মবিশ্বাসী ফটোগ্রাফার হয়েছি। মাস্টারক্লাসটি جامع এবং অনুসরণ করা সহজ।',
    avatar: 'https://placehold.co/80x80.png',
  },
];
