import type { Course, CourseCategory, Testimonial } from './types';
import { LayoutDashboard, Code, BarChart3, Palette, Camera, Mic2 } from 'lucide-react';

export const courseCategories: CourseCategory[] = [
  { name: 'Business', icon: BarChart3 },
  { name: 'Development', icon: Code },
  { name: 'Marketing', icon: Mic2 },
  { name: 'Design', icon: Palette },
  { name: 'IT & Software', icon: LayoutDashboard },
  { name: 'Photography', icon: Camera },
];

export const allCourses: Course[] = [
  {
    id: 1,
    title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
    description: 'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Router, Next.js, Best Practices and way more!',
    category: 'Development',
    level: 'Beginner',
    price: 84.99,
    duration: '48.5 hours',
    instructor: { name: 'Maximilian Schwarzmüller', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.6,
    reviewCount: 178000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Build powerful, fast, user-friendly and reactive web apps', 'Provide amazing user experiences by leveraging the power of JavaScript with ease', 'Apply for high-paid jobs or work as a freelancer in one the most demanded sectors you can find in web dev right now'],
    isFeatured: true,
  },
  {
    id: 2,
    title: 'The Complete 2024 Web Development Bootcamp',
    description: 'Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps.',
    category: 'Development',
    level: 'Beginner',
    price: 89.99,
    duration: '61.5 hours',
    instructor: { name: 'Dr. Angela Yu', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.7,
    reviewCount: 345000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Build any website you want.', 'Craft a portfolio of websites to apply for junior developer jobs.', 'Build fully-fledged websites and web apps for your startup or business.'],
    isFeatured: true,
  },
  {
    id: 3,
    title: 'The Ultimate Drawing Course - Beginner to Advanced',
    description: 'Learn the #1 most important building block of all art, Drawing. This course will teach you in a logical, easy to grasp way.',
    category: 'Design',
    level: 'Beginner',
    price: 49.99,
    duration: '11 hours',
    instructor: { name: 'Jaysen Batchelor', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.6,
    reviewCount: 111000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Draw objects out of your head', 'Understand the fundamentals of art', 'Draw realistic light and shadow'],
    isFeatured: true,
  },
  {
    id: 4,
    title: 'Digital Marketing Masterclass - 23 Courses in 1',
    description: 'Grow Your Business with Digital Marketing: Social Media Marketing, Content Marketing, SEO, YouTube, Email Marketing, Facebook, Ads & more',
    category: 'Marketing',
    level: 'Beginner',
    price: 94.99,
    duration: '34 hours',
    instructor: { name: 'Phil Ebiner', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.5,
    reviewCount: 88000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Grow a Business Online from Scratch', 'Make Money as a Digital Marketing Freelancer', 'Get Hired as a Digital Marketing Expert'],
    isFeatured: true,
  },
  {
    id: 5,
    title: 'Python for Data Science and Machine Learning Bootcamp',
    description: 'Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, Tensorflow, and more!',
    category: 'IT & Software',
    level: 'Intermediate',
    price: 99.99,
    duration: '25 hours',
    instructor: { name: 'Jose Portilla', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.6,
    reviewCount: 125000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Use Python for Data Science and Machine Learning', 'Implement Machine Learning Algorithms', 'Learn to use Pandas for Data Analysis'],
    isFeatured: false,
  },
  {
    id: 6,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    description: 'The Best Online Professional Photography Class: How to Take Amazing Photos for Beginners & Advanced Photographers.',
    category: 'Photography',
    level: 'Beginner',
    price: 94.99,
    duration: '23.5 hours',
    instructor: { name: 'Phil Ebiner', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.7,
    reviewCount: 65000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['You will know how to take amazing photos that impress your family and friends', 'You will know how the camera truly works, so you can take better photos using manual settings', 'You will know how to compose photos beautifully with basic photography rules'],
    isFeatured: false,
  },
  {
    id: 7,
    title: 'An Entire MBA in 1 Course: Award Winning Business School Prof',
    description: 'Everything you need to know about business from start-up to IPO. The most popular business course on Udemy!',
    category: 'Business',
    level: 'Beginner',
    price: 89.99,
    duration: '8.5 hours',
    instructor: { name: 'Chris Haroun', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.5,
    reviewCount: 75000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Supercharge your financial skills', 'Understand how monetary policy and fiscal policy work', 'Analyze company financials with ease'],
    isFeatured: false,
  },
  {
    id: 8,
    title: 'AWS Certified Solutions Architect - Associate 2024',
    description: 'Pass the AWS Certified Solutions Architect Associate Certification SAA-C03. Includes 2 practice tests!',
    category: 'IT & Software',
    level: 'Intermediate',
    price: 84.99,
    duration: '27 hours',
    instructor: { name: 'Stephane Maarek', avatar: 'https://placehold.co/40x40.png' },
    rating: 4.7,
    reviewCount: 220000,
    imageUrl: 'https://placehold.co/400x225.png',
    learningOutcomes: ['Pass the AWS Certified Solutions Architect Associate (SAA-C03) exam', 'Design and Deploy scalable, highly available, and fault tolerant systems on AWS', 'Become a Cloud Guru'],
    isFeatured: false,
  }
];

export const featuredCourses = allCourses.filter(course => course.isFeatured);

export const testimonials: Testimonial[] = [
  {
    name: 'Sarah Johnson',
    title: 'Web Developer',
    quote: 'The web development bootcamp was a game-changer for my career. The instructors were knowledgeable and the curriculum was perfectly paced.',
    avatar: 'https://placehold.co/80x80.png',
  },
  {
    name: 'Michael Chen',
    title: 'Data Analyst',
    quote: 'I was able to land my dream job after completing the Python for Data Science course. The hands-on projects were incredibly valuable.',
    avatar: 'https://placehold.co/80x80.png',
  },
  {
    name: 'Emily Rodriguez',
    title: 'UX/UI Designer',
    quote: 'Skill Navigator\'s design courses helped me build a strong portfolio. The community is supportive and the content is top-notch.',
    avatar: 'https://placehold.co/80x80.png',
  },
    {
    name: 'David Lee',
    title: 'Marketing Manager',
    quote: 'The digital marketing masterclass covered everything I needed to know. My company\'s online presence has grown significantly since.',
    avatar: 'https://placehold.co/80x80.png',
  },
  {
    name: 'Jessica Williams',
    title: 'Photographer',
    quote: 'I went from a complete beginner to a confident photographer. The masterclass is comprehensive and easy to follow.',
    avatar: 'https://placehold.co/80x80.png',
  },
];
